version: '3'

services:
  web:
    build: .
    ports:
      - "8033:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: phivedb
    ports:
      - "3314:3306"
    restart: unless-stopped
